field: aa69bfc6-16e6-4165-bbd6-75e46795733d # Landing Content
fieldLayouts:
  eedc9970-c353-4dd6-9590-e3d2fc09afac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: feb8d493-51e2-4efb-a0e4-b641e2c64337 # Number of Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e74e46ae-6bc6-447e-9727-3ee352fc89fa
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a0cc4a08-b0a9-4220-8ad7-72ce7f1c915f # Content Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12b0b790-f3ee-43aa-b847-17d6a3f91557
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b43c8469-478b-4d0d-8c1a-277df7f890fb # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18fc557c-19b8-49ec-b183-126b16b988c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44b90ead-cfc0-48fe-baa8-63d651af128f
        userCondition: null
fields:
  a0cc4a08-b0a9-4220-8ad7-72ce7f1c915f: # Content Header
    columnSuffix: ltennfmh
    contentColumnType: text
    fieldGroup: null
    handle: lccHeader
    instructions: null
    name: 'Content Header'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b43c8469-478b-4d0d-8c1a-277df7f890fb: # Content
    columnSuffix: ovhmzzwl
    contentColumnType: text
    fieldGroup: null
    handle: lccContent
    instructions: null
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 93fb68e0-cc2c-4f3f-90fd-b0182086bfa1 # Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  feb8d493-51e2-4efb-a0e4-b641e2c64337: # Number of Columns
    columnSuffix: yziyoddq
    contentColumnType: string
    fieldGroup: null
    handle: lccNumColumns
    instructions: null
    name: 'Number of Columns'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Two
            -
              - value
              - two
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Three
            -
              - value
              - three
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Four
            -
              - value
              - four
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: lColumnContent
name: 'Column Content'
sortOrder: 5
