field: e443c70e-6db5-423b-bd28-6ce9cc2cbb61 # Page Content
fieldLayouts:
  dab2fc95-fa41-44b5-88a5-cfdcd8c0f5ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0a54d1cd-ee98-4603-8dd9-8990d68138b0 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7df53cf5-14cc-44f9-9f05-13688a9ddc83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87bc5ddc-c6c6-49c2-805b-b3540b8eb8ce # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8103af64-5a0e-4345-9c0e-7d77e49d31f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e054236-0860-4da2-8231-7238e4144a55
        userCondition: null
fields:
  0a54d1cd-ee98-4603-8dd9-8990d68138b0: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  87bc5ddc-c6c6-49c2-805b-b3540b8eb8ce: # Attribution
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: null
    name: Attribution
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 5
