field: cb81b757-fe4f-4892-ae2e-7e5ea7522b26 # Sidebar
fieldLayouts:
  eeb61375-966b-4a28-bd72-4abc55fa155e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 238b2dd7-4c7f-44d1-b389-eb0e73d7fc13 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2245b13-d12b-4cae-bcd6-2fa7172cc1fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6de52b5-21c1-4366-81b1-cb4b8764b8ba
        userCondition: null
fields:
  238b2dd7-4c7f-44d1-b389-eb0e73d7fc13: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sharedSidebar
    instructions: null
    name: __blank__
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: 'Add sidebar'
      showSiteMenu: true
      sources:
        - 'section:a2d587c1-ef32-4193-8f69-c695ddc657a4' # Shared Sidebar
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: sharedSidebar
name: 'Shared Sidebar'
sortOrder: 2
