field: ee3e359f-97fb-4b27-b2e8-a8e94d5c3ad0 # Article Content
fieldLayouts:
  295a2f2d-6eb2-4424-a4d4-1548e6f882ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9cd14e55-f08e-4044-8c2b-69587551f1f2 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1529a55a-44a5-47c0-ab22-923cd71ad069
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17dc2240-0caa-45df-9aa5-4af1f9cdf53a # Add Drop Cap
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3ebd9e5-eb62-4686-a149-b5777e80a192
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b4283bfb-1158-4e3e-8435-a8cb3d73b9f7
        userCondition: null
fields:
  9cd14e55-f08e-4044-8c2b-69587551f1f2: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textArea
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms:
        - 1c0db3c0-b8d3-4af6-b93f-0d75e9b6d626 # Large Image
        - 5a9e2ae8-faa3-4e95-bd57-8c4068cf09f2 # Small Image
      availableVolumes: '*'
      ckeConfig: 93fb68e0-cc2c-4f3f-90fd-b0182086bfa1 # Default
      columnType: text
      defaultTransform: 5a9e2ae8-faa3-4e95-bd57-8c4068cf09f2 # Small Image
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  17dc2240-0caa-45df-9aa5-4af1f9cdf53a: # Add Drop Cap
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: addDropCap
    instructions: 'Usually, you should only ever use this on the first Text Area Block.'
    name: 'Add Drop Cap'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: textArea
name: 'Text Area'
sortOrder: 1
