fieldLayouts:
  1205c672-859d-445e-b9bf-c33adac60a2a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20e288fd-5e80-4057-8c85-7c9f9150bca6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7594ac16-be77-4220-9902-7cb02aa0055e # Sidebar Image
            instructions: null
            label: 'Card Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65197399-a7d0-46c7-ae2f-05b6d90ebdd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 23ea1c14-41d8-4b26-ae7f-c7083227b13f # Sidebar Header
            instructions: null
            label: 'Card Header'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3a940b1-0bac-4109-8877-97eb111d9fd7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 444bdc2f-c961-4fb6-ad22-9609e549feae # Sidebar Text
            instructions: null
            label: 'Card Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0899bd1c-c82f-4648-a3e0-0df7b5fdc4a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d1c604ad-9342-4819-bf3c-07ec0c31e7da # Sidebar Button
            instructions: null
            label: 'Card Button'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b79db9-dcef-4fa0-847d-306edd49e102
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 163ac82c-bbbf-4f53-9690-e5713ac5a62a
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9bf127bc-7523-4192-bdd8-fe46e10e4211 # Content Cards
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
