fieldLayouts:
  12431917-0309-4458-b3e1-f9273f1747dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92f134d7-12f3-4886-b310-b65ea3ffc672
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ec39d65-f93d-45ba-a821-2f2f58c2e54d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c95222e9-450c-431c-bd3a-d5f0d3111204
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4e856140-5d5d-4404-bf44-748428d1ce0a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 9434d20f-fc4b-4fe4-8793-7c71c4fdf040 # Hero Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a9ff289-e723-443b-bbb7-f71a4b920f74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cbea03a-b8a8-4ddb-b7db-4f38cf2b218e # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba2c8157-86e2-4c5a-8aec-ace730e71668
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04a6347e-01d0-47c2-a384-9358d1534b15 # Link List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74eb3583-41a6-4c83-8fe8-e7901f176843
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: d7bfafdd-d76a-41d3-924b-be4c6ea30d6a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 80580736-eca1-4c21-afef-b1b37b3d3808 # Homepage Content
            instructions: null
            label: 'Content Blocks'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22acdfd-b88f-4866-9a31-ae3e274f069c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: af6f9ce4-16a9-4e61-b216-3486f53d3dd8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 77c10bb4-cb7c-4539-aa55-740affa8e488 # Locations Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1c3e557-edc0-4b77-a5c7-cd19b0745ddd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6110132d-ee7c-4644-985f-d73ca7ea68be # Locations Rotator
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68dbab98-f2d4-4c73-aea4-07a6bad9759d
            userCondition: null
            warning: null
            width: 100
        name: Locations
        uid: 0a188bce-ceeb-4c55-8496-fa85e79438a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 36f2634b-ee6f-461a-8909-207a78d747df # Alert
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35a5326d-abc1-41c9-a8a4-645224803a58
            userCondition: null
            warning: null
            width: 100
        name: Alert
        uid: 47dd2670-705c-4c06-9588-d32328429e66
        userCondition: null
handle: homepage
hasTitleField: false
name: 'Homepage - Main'
section: 6451f8ed-ab88-477b-afbc-50b5307ea547 # Homepage - Main
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
