fieldLayouts:
  62760dca-bd56-4029-92c3-7425f984f1d6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f86e0985-7363-4272-8981-df4927b1f37f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 828a4c2f-e2f4-44b4-90a5-1f7b42b9964a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8ec39d65-f93d-45ba-a821-2f2f58c2e54d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64b08c1a-410b-4e1d-abe4-331446cde1e6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5000939c-89e2-4d6f-9834-1c687aab2a67 # Page Subheader
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc947723-5b0a-4df5-be68-54b936c446cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bf5b183-a3e2-40c5-8700-7432e9538c38 # Page Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f6558fb-fa2c-45c2-97cd-a8dac8f3a9b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 008e770f-a3a4-434a-b63b-1b8708ed1e0a # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f795e63c-a8b9-4738-83da-a0c0107421b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7da08252-c18f-4816-bc22-c07aa6fbe1f2
            userCondition: null
          -
            elementCondition: null
            fieldUid: aa69bfc6-16e6-4165-bbd6-75e46795733d # Landing Content
            instructions: null
            label: 'Content Blocks'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ce98325-bafc-4324-8af2-cbb2359e08e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13de660b-93bc-4b02-bbfd-2950b1174118
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This field will override the Call To Action set in the Globals section. Leave blank to use the global call to action.'
            type: craft\fieldlayoutelements\Tip
            uid: 09a51fc1-6e3b-4025-83ce-c6188a911bcd
            userCondition: null
          -
            elementCondition: null
            fieldUid: a6b28964-bd73-45f3-a6f1-209fdaa99cff # Call To Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd6139a1-e0ff-47bd-bb3f-8ff6756cd762
            userCondition: null
            warning: null
            width: 100
        name: 'Call To Action'
        uid: ea59a31b-0101-4717-bf42-4e731075ef71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fd07fef-7348-4b4c-befd-c5223fd96a24 # Hide From Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4c77f3f-222d-47cc-a1c4-8ace8eb346e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 94e5ec40-f58e-4d16-b141-22f01c42fb7f
            userCondition: null
          -
            elementCondition: null
            fieldUid: eeab7427-1cf0-4e89-9c47-8a728055aa59 # Internal Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a6d1854-e015-4d55-9ce8-dabae7023d0c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 361fc348-788e-4919-9220-4a9f92326eb0 # External Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40f9b92a-2ff9-489a-adc2-87efee6870e4
            userCondition: null
            warning: null
            width: 50
        name: Utilities
        uid: 1a3325bd-f500-41d3-afae-5548ed7b7a67
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2ee82f0-cd65-4af1-98ba-7ad7159079b1 # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 642d082c-672e-4789-992d-2ddaa0ebc478
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Settings'
        uid: 0e6823eb-1775-49ed-b963-8c57ef77297d
        userCondition: null
handle: landingPage
hasTitleField: true
name: 'Landing Page'
section: 4d63c242-f66b-49ba-afd6-b9c650174a3c # Design Standards
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
