fieldLayouts:
  803aef19-8a1d-4142-ad5b-a5884f69c0ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f7bd720-04e5-4dd8-8fa8-4db651ceb6a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b314a350-f7ff-4c9b-94a1-5e8627d87ca7
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8ec39d65-f93d-45ba-a821-2f2f58c2e54d # Banner Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4415143-90ab-432f-8f53-ca3993d289fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5000939c-89e2-4d6f-9834-1c687aab2a67 # Page Subheader
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8396e67-f3c4-4637-93fe-33dc2876b9d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bf5b183-a3e2-40c5-8700-7432e9538c38 # Page Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c29626cc-7a79-4674-9fbc-f2220bedea48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 008e770f-a3a4-434a-b63b-1b8708ed1e0a # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56e5f9cb-e670-4e69-ae7a-29f17d6cbde4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 25b0ee5f-8f96-493d-93fd-055d4e4d0cb1
            userCondition: null
          -
            elementCondition: null
            fieldUid: aa69bfc6-16e6-4165-bbd6-75e46795733d # Landing Content
            instructions: null
            label: 'Content Blocks'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57b007a8-5189-4b8e-adf1-d23fbd3411e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec2e6c71-a90c-4194-8f1d-ca0431b4ba2b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This field will override the Call To Action set in the Globals section. Leave blank to use the global call to action.'
            type: craft\fieldlayoutelements\Tip
            uid: 4a1eaa91-b573-4d92-a132-8c249b917820
            userCondition: null
          -
            elementCondition: null
            fieldUid: a6b28964-bd73-45f3-a6f1-209fdaa99cff # Call To Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c738bf8-0d28-42c6-918b-9882a39b4c3b
            userCondition: null
            warning: null
            width: 100
        name: 'Call To Action'
        uid: 7e32bc40-9e39-4176-b964-d57868544aa4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fd07fef-7348-4b4c-befd-c5223fd96a24 # Hide From Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15575a75-3661-4357-a194-a54c46e42a3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e18b41cd-07a7-406e-999d-41bd8f90b9b7
            userCondition: null
          -
            elementCondition: null
            fieldUid: eeab7427-1cf0-4e89-9c47-8a728055aa59 # Internal Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18ae08b1-7db9-40b3-af72-f50ffed33ba0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 361fc348-788e-4919-9220-4a9f92326eb0 # External Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01581a52-9df3-46f9-837f-968af8c265be
            userCondition: null
            warning: null
            width: 50
        name: Utilities
        uid: b3b67b40-5f25-4c74-b310-39e8a3f7b571
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2ee82f0-cd65-4af1-98ba-7ad7159079b1 # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e41b962f-07fe-4007-9cc4-2a9bab1d1678
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Settings'
        uid: a96be40f-449c-43db-9b13-abf57bd47b0e
        userCondition: null
handle: landingPage
hasTitleField: true
name: 'Landing Page'
section: cfe2ab11-e0d6-4828-9b60-768ca1081018 # Navigation - Main
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
