fieldLayouts:
  5d00734d-dbd2-4e4a-8dd4-4405285d5d15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 83262117-8a40-4907-904a-61af955098c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5000939c-89e2-4d6f-9834-1c687aab2a67 # Page Subheader
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae708fec-3b44-477b-835a-dff057430edc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bf5b183-a3e2-40c5-8700-7432e9538c38 # Page Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd85d2c6-699d-473f-9f1c-b27f3eee6b76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 008e770f-a3a4-434a-b63b-1b8708ed1e0a # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09c9de80-9a83-4753-9226-2fc1e8bb23b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 05ae3831-fa5f-4ce2-9dd3-13fd5b28d441
            userCondition: null
          -
            elementCondition: null
            fieldUid: e443c70e-6db5-423b-bd28-6ce9cc2cbb61 # Page Content
            instructions: null
            label: 'Content Blocks'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f594af3-0819-4eee-84f4-cb362d71d6e8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5cc42252-a10a-4800-bcff-128d478e7b0c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cb81b757-fe4f-4892-ae2e-7e5ea7522b26 # Sidebar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01e464ec-a88e-4f90-b101-e8467bbcd422
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: 48ff6487-2180-4a9a-8e81-3227b9366092
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0ebd966a-c731-4c35-ab55-e4a45bbf57fb # Feature
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5114cbcb-9f14-42cf-abf7-0caff5759216
            userCondition: null
            warning: null
            width: 100
        name: Feature
        uid: 31bea627-545c-47a9-b7d6-f343b66c03bd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This field will override the Call To Action set in the Globals section. Leave blank to use the global call to action.'
            type: craft\fieldlayoutelements\Tip
            uid: 392a17b4-e7e2-4337-a48a-bdb8fded3efd
            userCondition: null
          -
            elementCondition: null
            fieldUid: a6b28964-bd73-45f3-a6f1-209fdaa99cff # Call To Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af175214-da7f-4cdb-a64d-567dba8f8def
            userCondition: null
            warning: null
            width: 100
        name: 'Call To Action'
        uid: fcdb207f-20f9-4d3a-86c4-80aa40e8e83a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fd07fef-7348-4b4c-befd-c5223fd96a24 # Hide From Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf4596c6-8e2d-453a-b616-173c0e432a9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 92f2968a-36cb-44f3-81cf-90b920f21365
            userCondition: null
          -
            elementCondition: null
            fieldUid: eeab7427-1cf0-4e89-9c47-8a728055aa59 # Internal Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 064f52c7-0594-4c7a-bd00-e97cc6f31ade
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 361fc348-788e-4919-9220-4a9f92326eb0 # External Redirect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e5a0aa7-6b1a-4ba2-9f7b-06325b7e4ab0
            userCondition: null
            warning: null
            width: 50
        name: Utilities
        uid: ab028997-f452-46f7-8fbd-10f46704d978
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2ee82f0-cd65-4af1-98ba-7ad7159079b1 # SEO Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef485520-bf8d-45a1-bd44-67e91ceb41a3
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Settings'
        uid: 87bc102c-52f5-4a57-8d55-a2189ff4c698
        userCondition: null
handle: mainNavigation
hasTitleField: true
name: 'Content Page'
section: cfe2ab11-e0d6-4828-9b60-768ca1081018 # Navigation - Main
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
