css: '@import "/stylesheets/ckeditor.css"'
headingLevels:
  - 2
  - 3
  - 4
name: Full
options:
  code:
    indentSequence: '  '
  image:
    toolbar:
      - 'imageStyle:alignBlockLeft'
      - 'imageStyle:alignCenter'
      - 'imageStyle:alignBlockRight'
      - '|'
      - toggleImageCaption
      - imageTextAlternative
  link:
    addTargetToExternalLinks: false
    decorators:
      openInNewTab:
        attributes:
          target: _blank
        label: 'Open in a new tab'
        mode: manual
      preventTracking:
        attributes:
          rel: 'noopener noreferrer'
        label: 'Prevent SEO crawling'
        mode: manual
  style:
    definitions:
      -
        classes:
          - small-header
        element: p
        name: 'Small Header (Eyebrow)'
      -
        classes:
          - largetext
        element: p
        name: 'Large Text'
      -
        classes:
          - button
        element: p
        name: 'Dark (Primary) Button'
      -
        classes:
          - white-button
        element: p
        name: 'White Button'
      -
        classes:
          - arrow-link
        element: p
        name: 'Link with Arrow'
toolbar:
  - sourceEditing
  - '|'
  - heading
  - '|'
  - style
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
  - insertImage
  - horizontalLine
