columnSuffix: null
contentColumnType: string
fieldGroup: eee1b2bc-0e51-477d-a3ab-5b0f0b0849fe # Homepage
handle: alert
instructions: null
name: Alert
searchable: true
settings:
  contentTable: '{{%matrixcontent_alert}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
