columnSuffix: null
contentColumnType: string
fieldGroup: a0fe5b36-2aa4-45c6-aa52-4f2b211d203b # Common
handle: articleListing
instructions: null
name: 'Article Listing'
searchable: true
settings:
  contentTable: '{{%matrixcontent_articlelisting}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
