columnSuffix: null
contentColumnType: text
fieldGroup: c2f30dbc-032d-4ca3-a7dd-dc80469e7183 # General Directory
handle: dirSortName
instructions: ''
name: 'Sort Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
