columnSuffix: null
contentColumnType: string(1000)
fieldGroup: c2f30dbc-032d-4ca3-a7dd-dc80469e7183 # General Directory
handle: dirShortDescription
instructions: 'A short description that will appear on the card.'
name: 'Short Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 250
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
