columnSuffix: null
contentColumnType: string
fieldGroup: a0fe5b36-2aa4-45c6-aa52-4f2b211d203b # Common
handle: feature
instructions: null
name: Feature
searchable: true
settings:
  contentTable: '{{%matrixcontent_feature}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
