columnSuffix: null
contentColumnType: text
fieldGroup: a0fe5b36-2aa4-45c6-aa52-4f2b211d203b # Common
handle: introduction
instructions: 'Optionally include an introductory block of text. This should be kept to 1-to-2 sentences.'
name: Introduction
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 2
  multiline: 1
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
