columnSuffix: null
contentColumnType: text
fieldGroup: ae5efb3a-2ce9-4bea-a606-d71f9faee980 # Team
handle: jobTitle
instructions: ''
name: 'Job Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
