columnSuffix: null
contentColumnType: text
fieldGroup: 50457ffa-e50e-4b28-a515-7a099e2204af # Events
handle: location
instructions: ''
name: Location
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 394290e3-acd0-43fe-a489-c9b3a464da29 # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
