columnSuffix: null
contentColumnType: text
fieldGroup: 2cb00cdf-4694-41cb-9d13-a155748c4df8 # Errors
handle: pageNotFoundError
instructions: ''
name: '404 Page Not Found Error'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 93fb68e0-cc2c-4f3f-90fd-b0182086bfa1 # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
