columnSuffix: null
contentColumnType: text
fieldGroup: ae5efb3a-2ce9-4bea-a606-d71f9faee980 # Team
handle: phoneNumber
instructions: ''
name: 'Phone Number'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. 401-555-5555'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
