columnSuffix: null
contentColumnType: text
fieldGroup: d2675e11-a907-490e-9054-e8230587241c # Template
handle: quickLinksHeader
instructions: null
name: 'Quick Links Header'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
