columnSuffix: null
contentColumnType: string
fieldGroup: d2675e11-a907-490e-9054-e8230587241c # Template
handle: quickLinks
instructions: ''
name: 'Quick Links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_quicklinks}}'
  maxBlocks: '5'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
