columnSuffix: null
contentColumnType: text
fieldGroup: c8cafcba-fd75-43a8-b29b-3c05d5edb2ce # SEO
handle: seoSettings
instructions: null
name: 'SEO Settings'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogTitle
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterTitle
    - twitterDescription
    - twitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
