columnSuffix: null
contentColumnType: string
fieldGroup: 96cc2c98-ff02-48eb-ae38-f6f12745a1dd # Sidebar
handle: sidebarImage
instructions: '16:9 aspect ratio'
name: 'Sidebar Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:09c09568-4b70-4b1a-a334-24e0b0a5ed09' # Content Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:09c09568-4b70-4b1a-a334-24e0b0a5ed09' # Content Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:09c09568-4b70-4b1a-a334-24e0b0a5ed09' # Content Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
