fieldLayouts:
  e8708ae7-85c9-4c7c-8f3d-0a49253d21db:
    tabs:
      -
        elements:
          -
            fieldUid: cf025d69-aa77-4586-a6a6-3f1e14fdfa84 # Header Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86173fea-bb3c-4971-a0d8-213318793f2a # Body Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO & Tracking'
        sortOrder: 1
handle: adminSettings
name: 'Admin Settings'
sortOrder: 2
