defaultPlacement: end
enableVersioning: true
handle: categories
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  33e15c65-c8eb-45e6-a385-b793d2fcc64d: # Client Name
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 35ef4c15-1b13-4fef-b61c-e51b20641994
type: structure
