defaultPlacement: end
enableVersioning: true
handle: departments
name: Departments
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  33e15c65-c8eb-45e6-a385-b793d2fcc64d: # Client Name
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 155b44c0-c951-4507-ad91-24b82db83bf6
type: structure
