defaultPlacement: end
enableVersioning: true
handle: designStandards
name: 'Design Standards'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  33e15c65-c8eb-45e6-a385-b793d2fcc64d: # Client Name
    enabledByDefault: true
    hasUrls: true
    template: main/page/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 13324f89-5878-4576-9b6f-b7e7076f78e6
type: structure
