defaultPlacement: end
enableVersioning: true
handle: mainNavigation
name: 'Navigation - Main'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  33e15c65-c8eb-45e6-a385-b793d2fcc64d: # Client Name
    enabledByDefault: true
    hasUrls: true
    template: main/page/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 57711349-0602-46e2-80de-c5b1ee5747d9
type: structure
