defaultPlacement: end
enableVersioning: true
handle: team
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  33e15c65-c8eb-45e6-a385-b793d2fcc64d: # Client Name
    enabledByDefault: true
    hasUrls: true
    template: main/page/_entry
    uriFormat: 'team/{slug}'
type: channel
